default: &default
  host: localhost
  encoding: unicode
  adapter: postgis
  pool: 5
  timeout: 5000
  username: postgres
  database: rs_development

development:
  <<: *default

test:
  <<: *default
  database: rs_test

production:
  <<: *default
  database: rs_production

staging:
  <<: *default
  database: rs_staging

